### ISSUE TITLE
Errors while executing

### ISSUE THREAD

**Issue by Juergen-Coding** [cwensley/pablodraw#92] opened 2023-06-22 12:07 UTC
System:
  Kernel: 6.0.7-1-default arch: x86_64 bits: 64 Desktop: Xfce v: 4.16.1
    Distro: openSUSE Tumbleweed 20221106

`./PabloDraw 
An error occurred.  Please report this information to https://github.com/cwensley/pablodraw/issues:
System.NullReferenceException: Arg_NullReferenceException
   at GLib.GType.op_Explicit(Type)
   at GLib.Object.ClassInitializer.AddProperties(IntPtr)
   at GLib.Object.ClassInitializer.ClassInit(IntPtr)

(PabloDraw:23903): GLib-GObject-CRITICAL **: 13:56:43.948: g_object_new_is_valid_property: object class '__gtksharp_5_Eto_GtkSharp_Forms_GtkShrinkableVBox' has no property named 'homogeneous'

(PabloDraw:23903): GLib-GObject-WARNING **: 13:56:43.951: ../gobject/gsignal.c:2517: signal 'destroy' is invalid for instance '0x55bdf8552480' of type '__gtksharp_5_Eto_GtkSharp_Forms_GtkShrinkableVBox'

(PabloDraw:23903): Gtk-CRITICAL **: 13:56:43.952: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(PabloDraw:23903): Gtk-CRITICAL **: 13:56:43.954: gtk_box_pack: assertion 'GTK_IS_WIDGET (child)' failed

(PabloDraw:23903): Gtk-CRITICAL **: 13:56:43.964: gtk_box_pack: assertion 'GTK_IS_BOX (box)' failed

(PabloDraw:23903): GLib-GObject-CRITICAL **: 13:56:43.967: g_object_new_is_valid_property: object class '__gtksharp_6_Eto_GtkSharp_Forms_EtoVBox' has no property named 'homogeneous'

(PabloDraw:23903): GLib-GObject-WARNING **: 13:56:43.967: ../gobject/gsignal.c:2517: signal 'destroy' is invalid for instance '0x55bdf8553040' of type '__gtksharp_6_Eto_GtkSharp_Forms_EtoVBox'

(PabloDraw:23903): Gtk-CRITICAL **: 13:56:43.967: gtk_box_pack: assertion 'GTK_IS_BOX (box)' failed

(PabloDraw:23903): Gtk-CRITICAL **: 13:56:43.967: gtk_box_pack: assertion 'GTK_IS_BOX (box)' failed
Unhandled exception. System.NullReferenceException: Arg_NullReferenceException
   at GLib.GType.op_Explicit(Type)
   at GLib.Object.ClassInitializer.AddProperties(IntPtr)
   at GLib.Object.ClassInitializer.ClassInit(IntPtr)
Abgebrochen (Speicherabzug geschrieben)
 `

**Comment by cwensley** [comment] 2023-06-26 15:25
Dupe of #91

**Closed by cwensley** 2023-06-26 15:25 UTC
