### ISSUE TITLE
Palette leakage

### ISSUE THREAD

**Issue by ericolito** [cwensley/pablodraw#27] opened 2021-01-26 14:52 UTC
If you alter the palette and use darker colours (value 18 and under) the saved files get corrupted with colour leakage all over.

**Comment by cwensley** [comment] 2021-01-27 03:42
Hey @ericolito, thanks for reporting the issue.

Are you modifying a color, or adding a color?  Can you provide steps that show what you are doing?

**Comment by ericolito** [comment] 2021-01-27 18:42
Hi @cwensley, thanks for getting back to me!

It doesn't seem to matter wheter I'm modifying or adding a new colour. The problem is easy to reproduce as it happens every time you turn the colour dark enough (i think the threshold is about value 19) - atleast when you use the colour as a background colour.

In this example i darkened the colour of the building in the background (to a value 12), saved the file as .ans and then reopened the file to find it looking like this: [https://skapar.com/~hellbeard/eto.png](url)

**Comment by cwensley** [comment] 2021-01-27 19:15
Hey @ericolito,

Great, thanks for the info!  Could you provide a sample .ans file that I can use to reproduce the issue?  It would be extremely helpful.

**Comment by ericolito** [comment] 2021-01-27 19:56
@cwensley 
Here's the file that I used as an example. Let me know if I can do anything (besides coding) to help. :) https://skapar.com/~hellbeard/havana.ans

**Comment by cwensley** [comment] 2021-01-31 04:39
Ah, looks like this is already fixed.  I can replicate the issue with 3.2.1, but not the latest code.  Could you try the [alpha release](https://github.com/cwensley/pablodraw/releases/tag/3.3.0-alpha1) to see if it's fixed for you as well?

**Comment by ericolito** [comment] 2021-01-31 16:38
That totally did it, it's working now! Thanks a lot for the effort, I really appreciate it. On the other hand I've run into some minor problems with the gtk3 interface but I guess it's still a work in progress..

**Comment by cwensley** [comment] 2021-02-01 02:56
Sweet!  Glad it works for you.  I'm going through things and fixing as necessary but if you do find any issues it would be greatly helpful to report them.

**Comment by cwensley** [comment] 2021-02-01 02:56
Closing as fixed.

**Closed by cwensley** 2021-02-01 02:56 UTC
