### ISSUE TITLE
Crashing whenever I try to copy and paste

### ISSUE THREAD

**Issue by nolageek** [cwensley/pablodraw#74] opened 2023-01-21 20:24 UTC
Crashing whenever I try to copy and paste anything. Windows 10 64bit

```
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data)
   at Eto.WinForms.Forms.ClipboardHandler.Update()
   at Eto.WinForms.Forms.DataObjectHandler`2.SetData(Byte[] value, String type)
   at Eto.Forms.Clipboard.SetData(Byte[] value, String type)
   at Eto.Forms.Clipboard.SetDataStream(Stream stream, String type)
   at Pablo.Formats.Character.Actions.Block.CopyToClipboard.OnExecuted(EventArgs e) in D:\a\pablodraw\pablodraw\Source\Pablo\Formats\Character\Actions\Block\CopyToClipboard.cs:line 66
   at Eto.Forms.Command.Execute()
   at Eto.Forms.Command.System.Windows.Input.ICommand.Execute(Object parameter)
   at Eto.PropertyStore.CommandWrapper.Command_Execute(Object sender, EventArgs e)
   at Eto.Forms.MenuItem.OnClick(EventArgs e)
   at Eto.Forms.MenuItem.PerformClick()
   at Pablo.Interface.Main.OnKeyDown(KeyEventArgs e) in D:\a\pablodraw\pablodraw\Source\Pablo.Interface\Main.cs:line 469
   at Eto.Forms.Control.Callback.OnKeyDown(Control widget, KeyEventArgs e)
   at Eto.WinForms.Forms.ApplicationHandler.<>c.<SetOptions>b__25_8(Control c, ICallback cb, KeyEventArgs e)
   at Eto.WinForms.BubbleEventFilter.KeyEvent(BubbleEventArgs be, Action`3 action, KeyEventType keyEventType)
   at Eto.WinForms.BubbleEventFilter.<>c__DisplayClass4_0.<AddBubbleKeyEvent>b__0(BubbleEventArgs be)
   at Eto.WinForms.BubbleEventFilter.PreFilterMessage(Message& message)
   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.Interop.Mso.IMsoComponent.FPreTranslateMessage(MSG* msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Eto.WinForms.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run()
   at PabloDraw.CommandHandlers.EditorCommandLine.Process(ProcessCommandLineArgs args) in D:\a\pablodraw\pablodraw\Source\PabloDraw\CommandHandlers\EditorCommandLine.cs:line 79
```

**Comment by nolageek** [comment] 2023-02-15 05:16
Still crashing constantly

System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data)
   at Eto.WinForms.Forms.ClipboardHandler.Update()
   at Eto.WinForms.Forms.DataObjectHandler`2.SetData(Byte[] value, String type)
   at Eto.Forms.Clipboard.SetData(Byte[] value, String type)
   at Eto.Forms.Clipboard.SetDataStream(Stream stream, String type)
   at Pablo.Formats.Character.Actions.Block.CutToClipboard.Execute(CommandExecuteArgs args) in D:\a\pablodraw\pablodraw\Source\Pablo\Formats\Character\Actions\Block\CutToClipboard.cs:line 71
   at Pablo.PabloCommand.OnExecuted(EventArgs e) in D:\a\pablodraw\pablodraw\Source\Pablo\PabloCommand.cs:line 101
   at Eto.Forms.Command.Execute()
   at Eto.Forms.Command.System.Windows.Input.ICommand.Execute(Object parameter)
   at Eto.PropertyStore.CommandWrapper.Command_Execute(Object sender, EventArgs e)
   at Eto.Forms.MenuItem.OnClick(EventArgs e)
   at Eto.Forms.MenuItem.PerformClick()
   at Pablo.Interface.Main.OnKeyDown(KeyEventArgs e) in D:\a\pablodraw\pablodraw\Source\Pablo.Interface\Main.cs:line 469
   at Eto.Forms.Control.Callback.OnKeyDown(Control widget, KeyEventArgs e)
   at Eto.WinForms.Forms.ApplicationHandler.<>c.<SetOptions>b__25_8(Control c, ICallback cb, KeyEventArgs e)
   at Eto.WinForms.BubbleEventFilter.KeyEvent(BubbleEventArgs be, Action`3 action, KeyEventType keyEventType)
   at Eto.WinForms.BubbleEventFilter.<>c__DisplayClass4_0.<AddBubbleKeyEvent>b__0(BubbleEventArgs be)
   at Eto.WinForms.BubbleEventFilter.PreFilterMessage(Message& message)
   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.Interop.Mso.IMsoComponent.FPreTranslateMessage(MSG* msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Eto.WinForms.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run()
   at PabloDraw.CommandHandlers.EditorCommandLine.Process(ProcessCommandLineArgs args) in D:\a\pablodraw\pablodraw\Source\PabloDraw\CommandHandlers\EditorCommandLine.cs:line 79

**Comment by cwensley** [comment] 2023-03-11 17:59
Closing as duplicate of #36

**Closed by cwensley** 2023-03-11 17:59 UTC
